travis:
  secure:
    BINSTAR_TOKEN: Ox+Y403SvrosOXgerSsr0Q0o8alTCb15wGsU247B0z3gwCTFR4c5yVSi9QiX2XHn3u8UaLYrJEwpcXYe/cYk1lzJM1IpRiOcJw5vml02srjtFXqbN+vzUwKq/7N4oUMBLfEk5uJ8VqyMW3Le6ehkb7MCwF0T6dW5LcBFuxJQ13fceWvFkXJltUuxYqR2wvNpYRK5tRQKsfU9HLuge6RVZo0z/fu5BB5rMKFCDXsExvhNt3yayeb43pFXvPM9/LTeV1WxW9NSpVjko2BaILqCWhmd4OyniHVWW0gncnOpYPKA531pSEnWuGu0WZru6f2FItGhCDKw8A/VTxE+TJqfiXCWcQjk1ve5oxnU9z91+z+79qS4QiW+TKpW/jYgjGV9aaGuv6UwchO6hf/5tKEj8zSKEnqL+RePG1+Vy87Vtnm5LLQvif/PTyq4C3Kg/dOqSIPjHBel0GAiyh2yKwjMuVJBmYEr2jRqAPknpOI8mUSev2+5TKLg8/5KEGAqEquYXCKRVwh2OIBK6mW3bJUDhzZd1w2UY+e3VMhyTylaVSEUT6WnPLb5R95fIMW5sXzi+a8lu5vAl6ox2qF/juscJJEZSc+k6WrAQRu9AO3sWe1tL2Qsbh9Qq4sf3NtppmKagKUhrZJbxptAW7DhmcnlWpKPSx2Xl++fWOckH7i25yM=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
